use super::*;

/// Build the markdown body for a rebuild PR. The summary line includes a
/// `(Z rolled back to archive)` parenthetical when `report.rolled_back >
/// 0` so the operator can confirm at a glance that the rollback count
/// matches the failure count; the failures section header describes
/// rollback rather than active-path retention to match the actual
/// behavior enforced by the rebuild's atomicity contract.
pub(crate) fn build_rebuild_pr_body(report: &crate::cli::sync_specs::RebuildReport) -> String {
    let mut body = String::new();
    body.push_str("This PR was generated by `autocoder sync-specs --rebuild`.\n\n");
    if report.rolled_back > 0 {
        body.push_str(&format!(
            "Replayed {} archived change(s) chronologically; {} succeeded, {} failed ({} rolled back to archive).\n\n",
            report.processed, report.successful, report.failed, report.rolled_back
        ));
    } else {
        body.push_str(&format!(
            "Replayed {} archived change(s) chronologically; {} succeeded, {} failed.\n\n",
            report.processed, report.successful, report.failed
        ));
    }
    if !report.failures.is_empty() {
        body.push_str(
            "**Failed changes** (rolled back to archive — see failure reasons below for the openspec output explaining each):\n",
        );
        for f in &report.failures {
            body.push_str(&format!(
                "- `{}`: {}\n",
                f.slug,
                truncate_one_line(&f.failure_reason, 200)
            ));
        }
        body.push('\n');
    }
    if !report.prefix_renames.is_empty() {
        body.push_str("**Applied dependency-prefix renames**:\n\n");
        body.push_str(&render_prefix_renames_markdown(&report.prefix_renames));
        body.push('\n');
    }
    body.push_str("**Canonical spec files**:\n");
    for sf in &report.spec_files {
        let tag = if sf.modified { "modified" } else { "unchanged" };
        body.push_str(&format!("- `{}` ({tag})\n", sf.path));
    }
    body
}

/// Build the implementer-summary markdown for `processed`, truncate it to
/// fit GitHub's comment limit, and POST it as an issue comment to the PR
/// (issues and PRs share the comments endpoint). Best-effort: any
/// failure is logged at ERROR; the caller's PR creation has already
/// succeeded and is not rolled back.
///
/// `api_base` is `github::DEFAULT_API_BASE` in production; tests pass a
/// mockito server URL instead.
#[allow(clippy::too_many_arguments)]
pub(crate) async fn post_implementer_summary_comment(
    paths: &DaemonPaths,
    api_base: &str,
    workspace: &Path,
    upstream_owner: &str,
    upstream_repo: &str,
    pr_number: u64,
    processed: &[String],
    token: &str,
) {
    let body = build_implementer_summary(paths, workspace, processed);
    if body.is_empty() {
        tracing::info!(
            pr_number,
            "skipping implementer-summary comment: no per-change run-log content available"
        );
        return;
    }
    let body = truncate_to_fit(body, 60_000);

    let result = if api_base == github::DEFAULT_API_BASE {
        github::create_issue_comment(upstream_owner, upstream_repo, pr_number, &body, token).await
    } else {
        #[cfg(test)]
        {
            github::create_issue_comment_at_for_test(
                api_base,
                upstream_owner,
                upstream_repo,
                pr_number,
                &body,
                token,
            )
            .await
        }
        #[cfg(not(test))]
        {
            unreachable!("non-default api_base is test-only");
        }
    };

    match result {
        Ok(()) => tracing::info!(
            pr_number,
            change_count = processed.len(),
            "posted implementer-summary comment"
        ),
        Err(e) => tracing::error!("posting implementer-summary comment failed: {e:#}"),
    }
}

/// Read each change's run-log from `<system-temp>/autocoder/logs/<workspace-basename>/<change>.log`,
/// extract the `=== STDOUT (n bytes) ===` block (only stdout — stderr is
/// operator log noise), and assemble a single markdown comment with one
/// section per change. If a log is unreadable, the change is skipped with
/// a WARN. If ALL changes' logs are unreadable, returns an empty string.
pub(crate) fn build_implementer_summary(
    paths: &DaemonPaths,
    workspace: &Path,
    processed: &[String],
) -> String {
    let timeout_fallback =
        "(executor timed out before final summary; see daemon log for action stream)";
    let mut sections = Vec::new();
    for change in processed {
        let path = crate::executor::claude_cli::run_log_path(paths, workspace, change);
        let raw = match std::fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!(
                    change = %change,
                    path = %path.display(),
                    "implementer-summary: skipping change — cannot read run-log: {e}"
                );
                continue;
            }
        };
        // Prefer the FINAL ANSWER section (JSON streaming mode). Fall
        // back to the legacy STDOUT section (text-mode opt-out OR a
        // legacy log carried over from before this change shipped).
        let body = if let Some(final_answer) = crate::executor::event_log::read_final_answer(&path)
        {
            final_answer
        } else if raw.contains("=== FINAL ANSWER (") {
            // FINAL ANSWER section present but empty → timeout-kill case.
            timeout_fallback.to_string()
        } else {
            let stdout = extract_stdout_section(&raw);
            let trimmed = stdout.trim_end();
            if trimmed.is_empty() {
                "_(no implementer output captured)_".to_string()
            } else {
                trimmed.to_string()
            }
        };
        sections.push(format!("### {change}\n\n{body}"));
    }

    if sections.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("## Agent implementation notes\n");
    out.push_str("<!-- Generated by autocoder; the agent's end-of-run output for each\n");
    out.push_str("     change in this pass. Reviewer is the separate `## Code Review`\n");
    out.push_str("     section in the PR body. -->\n\n");
    out.push_str(&sections.join("\n\n"));
    out
}

/// Slice out the bytes between the `=== STDOUT (n bytes) ===` header and
/// the next `=== STDERR (` header (or end-of-file). The match on the
/// STDOUT header is anchored on the literal prefix to tolerate the
/// variable byte-count in the parens. Returns an empty string if the
/// STDOUT header is absent.
pub(crate) fn extract_stdout_section(raw: &str) -> &str {
    let stdout_marker = "=== STDOUT (";
    let stderr_marker = "=== STDERR (";
    let stdout_idx = match raw.find(stdout_marker) {
        Some(i) => i,
        None => return "",
    };
    // Advance past the header line.
    let after_header = match raw[stdout_idx..].find('\n') {
        Some(nl) => stdout_idx + nl + 1,
        None => return "",
    };
    let end = match raw[after_header..].find(stderr_marker) {
        Some(rel) => after_header + rel,
        None => raw.len(),
    };
    &raw[after_header..end]
}

/// Truncate `body` to fit within GitHub's comment size limit. If `body`
/// is short enough, returned as-is. Otherwise truncated at the largest
/// char boundary `<= max` and a marker noting the truncation is appended.
///
/// `pub(crate)` so the revision success-comment composer
/// (`revisions::compose_revision_success_comment`) can reuse the same
/// limit-and-marker behavior. The marker text is generalized (it does
/// not say "implementer") because it now serves both the implementer
/// summary AND the revision summary; both recover the full output from
/// the same per-change run-log path.
pub(crate) fn truncate_to_fit(body: String, max: usize) -> String {
    if body.len() <= max {
        return body;
    }
    let mut cut = max;
    while cut > 0 && !body.is_char_boundary(cut) {
        cut -= 1;
    }
    let mut truncated = body[..cut].to_string();
    truncated.push_str(
        "\n\n_[summary truncated to fit GitHub comment limit; full output at <logs_dir>/runs/<workspace-basename>/<change>.log]_",
    );
    truncated
}

/// Replace hyphens in `slug` with spaces. If the slug carries the
/// stacked `aNN-` prefix convention (`^[a-z]+\d+-`), keep that prefix as
/// a leading label followed by `": "` and the de-hyphenated remainder.
/// Otherwise just swap hyphens for spaces wholesale.
pub(crate) fn humanize_slug(slug: &str) -> String {
    let re = regex::Regex::new(r"^([a-z]+\d+)-(.+)$").expect("static regex compiles");
    if let Some(caps) = re.captures(slug) {
        let prefix = &caps[1];
        let rest = caps[2].replace('-', " ");
        format!("{prefix}: {rest}")
    } else {
        slug.replace('-', " ")
    }
}

/// Build a PR title from the list of changes processed in a pass.
/// Single-change passes get the humanized slug; multi-change passes get
/// `<first humanized> (+N more)`. Total length is capped at ~80 chars,
/// with an ellipsis replacing the truncated tail.
pub(crate) fn build_pr_title(changes: &[String]) -> String {
    const MAX_LEN: usize = 80;
    const ELLIPSIS: char = '…';

    if changes.is_empty() {
        return "agent: empty pass".to_string();
    }
    let first = humanize_slug(&changes[0]);
    let title = if changes.len() == 1 {
        first
    } else {
        format!("{first} (+{} more)", changes.len() - 1)
    };

    if title.chars().count() <= MAX_LEN {
        return title;
    }

    // Truncate at a char boundary so we don't slice through a multibyte
    // codepoint. Leave room for the ellipsis itself.
    let take = MAX_LEN.saturating_sub(1);
    let truncated: String = title.chars().take(take).collect();
    let mut out = truncated;
    out.push(ELLIPSIS);
    out
}

pub(crate) fn build_pr_body(
    workspace: &Path,
    changes: &[String],
    includes_self_heal: bool,
) -> String {
    let mut s = String::new();
    if includes_self_heal {
        s.push_str(
            "_This PR archives one or more changes whose implementation was already present on the base branch. No code diff is included; only the openspec archive move._\n\n",
        );
    }
    for change in changes {
        let why = read_change_why(workspace, change);
        let body = match why {
            Some(w) if !w.trim().is_empty() => w.trim().to_string(),
            _ => "_(no proposal.md available)_".to_string(),
        };
        s.push_str(&format!("## {change}\n\n{body}\n\n"));
    }
    s.push_str("Changes implemented in this pass:\n\n");
    for change in changes {
        s.push_str(&format!("- {change}\n"));
    }
    s
}

/// Parse audit-produced commit subjects of shape
/// `audit: <type> proposals (<N> change(s))` and return `(total, types)`:
/// the sum of `N` across all matching subjects AND the deduplicated list
/// of audit types preserving first-seen order. Subjects not matching the
/// canonical shape contribute nothing to the totals (they are listed
/// verbatim in the PR body, but the title summary skips them).
fn summarize_audit_commit_subjects(subjects: &[String]) -> (u32, Vec<String>) {
    let re = match regex::Regex::new(r"^audit: (?P<type>\S+) proposals \((?P<n>\d+) change\(s\)\)$")
    {
        Ok(r) => r,
        Err(_) => return (0, Vec::new()),
    };
    let mut total: u32 = 0;
    let mut types: Vec<String> = Vec::new();
    for s in subjects {
        if let Some(caps) = re.captures(s) {
            if let Ok(n) = caps["n"].parse::<u32>() {
                total = total.saturating_add(n);
            }
            let t = caps["type"].to_string();
            if !types.contains(&t) {
                types.push(t);
            }
        }
    }
    (total, types)
}

/// Buckets agent-branch commits go into for content-aware PR-body
/// rendering (a38). Each bucket holds the verbatim commit subjects that
/// matched its category prefix; the renderer enumerates them under the
/// category's section AND only emits a section for non-empty buckets.
#[derive(Debug, Default, PartialEq, Eq)]
pub(crate) struct CommitCategories {
    /// `audit: <type> proposals (<N> change(s))` subjects (a20a3).
    pub(crate) audit: Vec<String>,
    /// `iteration <N> of <change>: <reason>` subjects (a27a1).
    pub(crate) iteration_wip: Vec<String>,
    /// Implementer-archived commits — `archive: <change>: ...` (self-heal)
    /// OR the canonical `<aNN-slug>: <why>` shape produced by
    /// [`build_commit_subject`].
    pub(crate) implementer: Vec<String>,
    /// Anything else (manual edits, merges, unrecognized prefixes).
    pub(crate) other: Vec<String>,
}

impl CommitCategories {
    fn total(&self) -> usize {
        self.audit.len() + self.iteration_wip.len() + self.implementer.len() + self.other.len()
    }

    /// Stable, human-friendly category labels for the PR title's
    /// "across <categories>" suffix (mixed-content title shape).
    fn nonempty_labels(&self) -> Vec<&'static str> {
        let mut out: Vec<&'static str> = Vec::new();
        if !self.audit.is_empty() {
            out.push("audit");
        }
        if !self.iteration_wip.is_empty() {
            out.push("iteration WIP");
        }
        if !self.implementer.is_empty() {
            out.push("implementer");
        }
        if !self.other.is_empty() {
            out.push("other");
        }
        out
    }
}

/// Categorize agent-branch commit subjects by message-prefix into the
/// buckets the audit-only PR body renderer uses. The match is
/// prefix-anchored; the categorizer is deliberately permissive — the
/// renderer treats unknown shapes as `other` rather than failing.
pub(crate) fn categorize_commit_subjects(subjects: &[String]) -> CommitCategories {
    // Lazily compile each pattern once per call. The renderer is a
    // hot-ish path (every PR opens), but not so hot that a static
    // OnceLock-cached regex pays its weight; keep it simple.
    let audit_re = regex::Regex::new(r"^audit: \S+ proposals \(\d+ change\(s\)\)$")
        .expect("static audit regex compiles");
    let iteration_re =
        regex::Regex::new(r"^iteration \d+ of \S+:").expect("static iteration regex compiles");
    let archive_re = regex::Regex::new(r"^archive: ").expect("static archive regex compiles");
    // `<aNN-slug>: <why>` from `build_commit_subject` — the aNN prefix
    // convention is enforced by the openspec change-name discipline.
    let implementer_re =
        regex::Regex::new(r"^[a-z]+\d+[a-z0-9-]*: ").expect("static implementer regex compiles");

    let mut cats = CommitCategories::default();
    for s in subjects {
        if audit_re.is_match(s) {
            cats.audit.push(s.clone());
        } else if iteration_re.is_match(s) {
            cats.iteration_wip.push(s.clone());
        } else if archive_re.is_match(s) || implementer_re.is_match(s) {
            cats.implementer.push(s.clone());
        } else {
            cats.other.push(s.clone());
        }
    }
    cats
}

/// PR title for the audit-only-PR path. When EVERY commit on the agent
/// branch matches the canonical `audit: <type> proposals (<N> change(s))`
/// shape, the title takes today's `audit-only: <N> proposal(s) from
/// <comma-separated-types>` form. When commits are mixed (audit + iteration
/// WIP + ...) OR when no audit commits exist (the defensive case — by
/// a38's suppression rule, an iteration with iteration-pending markers
/// shouldn't reach this renderer in production), the title falls back to
/// a generic `agent-q changes: <N> commits across <categories>` shape so
/// the title accurately describes what the PR contains.
pub(crate) fn build_audit_only_pr_title(commit_subjects: &[String]) -> String {
    const MAX_LEN: usize = 80;
    const ELLIPSIS: char = '…';
    let cats = categorize_commit_subjects(commit_subjects);
    let title = build_audit_only_pr_title_from_categories(commit_subjects, &cats);
    if title.chars().count() <= MAX_LEN {
        return title;
    }
    let take = MAX_LEN.saturating_sub(1);
    let truncated: String = title.chars().take(take).collect();
    let mut out = truncated;
    out.push(ELLIPSIS);
    out
}

/// Inner of [`build_audit_only_pr_title`] — works on already-categorized
/// commits. Pulled out so tests can drive the title shape from a
/// fixture `CommitCategories` directly without re-running the regex
/// match.
fn build_audit_only_pr_title_from_categories(
    commit_subjects: &[String],
    cats: &CommitCategories,
) -> String {
    let total = cats.total();
    if total == 0 {
        return "audit-only: agent-branch commits without implementer changes".to_string();
    }
    // Pure-audit case: today's canonical title.
    if !cats.audit.is_empty()
        && cats.iteration_wip.is_empty()
        && cats.implementer.is_empty()
        && cats.other.is_empty()
    {
        let (audit_total, types) = summarize_audit_commit_subjects(commit_subjects);
        if !types.is_empty() {
            return format!(
                "audit-only: {} proposal(s) from {}",
                audit_total,
                types.join(", "),
            );
        }
        // Audit commits present but none matched the proposals-counting
        // shape (unusual — would be an audit type that produced an audit
        // commit without proposal counts). Fall through to generic.
    }
    // Generic mixed-or-non-audit shape.
    let labels = cats.nonempty_labels();
    if labels.is_empty() {
        return "audit-only: agent-branch commits without implementer changes".to_string();
    }
    format!(
        "agent-q changes: {} commit(s) across {}",
        total,
        labels.join(", "),
    )
}

/// PR body for the audit-only-PR path. Partitions the agent-branch commit
/// subjects into categories (audit-produced, iteration WIP, implementer-
/// archived, other) AND emits one section per non-empty category. The
/// "audit-produced proposals only" framing is included ONLY when audit
/// commits actually exist — fixing PR #77's misleading body that named
/// "audit-produced proposals" with zero audit commits in the diff.
pub(crate) fn build_audit_only_pr_body(commit_subjects: &[String]) -> String {
    build_audit_only_pr_body_with_attribution(commit_subjects, None)
}

/// As [`build_audit_only_pr_body`], but appends a one-line model
/// attribution (a49) to the `## Audit-produced proposals` section when
/// `attribution_line` is `Some`. `attribution_line` is the fully-formed
/// `*Auditor (<audit-type>): <provider>/<model>*` line produced by
/// [`crate::attribution::audit_attribution_line`].
///
/// In-tree audits wrap the Claude CLI and have no daemon-known `(provider,
/// model)`, so the audit-only-PR path passes `None` today and no line is
/// emitted. The attributed seam exists for audits that gain a resolvable
/// model via the planned model-registry work; it is exercised by tests.
pub(crate) fn build_audit_only_pr_body_with_attribution(
    commit_subjects: &[String],
    attribution_line: Option<&str>,
) -> String {
    let cats = categorize_commit_subjects(commit_subjects);
    build_audit_only_pr_body_from_categories(&cats, attribution_line)
}

/// Inner of [`build_audit_only_pr_body`] — works on already-categorized
/// commits. Pulled out so tests can drive the body content from a
/// fixture `CommitCategories` directly. `attribution_line` (a49) is
/// appended to the `## Audit-produced proposals` section when `Some`.
fn build_audit_only_pr_body_from_categories(
    cats: &CommitCategories,
    attribution_line: Option<&str>,
) -> String {
    let mut s = String::new();

    // Lead sentence: framing depends on what's actually present.
    if cats.total() == 0 {
        s.push_str(
            "This PR was opened from the audit-only path but no commit subjects were readable from the agent branch.\n",
        );
        return s;
    }
    if !cats.audit.is_empty()
        && cats.iteration_wip.is_empty()
        && cats.implementer.is_empty()
        && cats.other.is_empty()
    {
        s.push_str(
            "This PR ships audit-produced proposals only — no implementer changes this iteration.\n\n",
        );
    } else {
        s.push_str(
            "This PR ships agent-branch commits from multiple sources. Sections below enumerate each category present in the diff.\n\n",
        );
    }

    if !cats.audit.is_empty() {
        s.push_str("## Audit-produced proposals\n\n");
        for subject in &cats.audit {
            s.push_str(&format!("- {subject}\n"));
        }
        // a49: attribute the model behind the audit-produced proposals.
        if let Some(line) = attribution_line {
            s.push_str(line);
            s.push('\n');
        }
        s.push('\n');
    }
    if !cats.iteration_wip.is_empty() {
        s.push_str("## Iteration WIP\n\n");
        s.push_str(
            "_The following commits are in-progress iteration work (a27a1). They are NOT ready to merge as-is; the iteration sequence has not concluded._\n\n",
        );
        for subject in &cats.iteration_wip {
            s.push_str(&format!("- {subject}\n"));
        }
        s.push('\n');
    }
    if !cats.implementer.is_empty() {
        s.push_str("## Implementer-archived changes\n\n");
        for subject in &cats.implementer {
            s.push_str(&format!("- {subject}\n"));
        }
        s.push('\n');
    }
    if !cats.other.is_empty() {
        s.push_str("## Other commits\n\n");
        for subject in &cats.other {
            s.push_str(&format!("- {subject}\n"));
        }
        s.push('\n');
    }

    if !cats.audit.is_empty() {
        s.push_str(
            "Each `audit: <type>` commit creates new `openspec/changes/<prefix>-*` directories that the next polling iteration will pick up via `list_pending` and route to the implementer.\n",
        );
    }
    s
}

/// Read a change's proposal `## Why` section, preferring the archive
/// location and falling back to the active path. Step 1 looks up
/// `<workspace>/openspec/changes/archive/*-<change>/proposal.md` (picking
/// the lexicographically last match if multiple exist). Step 2, on
/// archive miss, tries `<workspace>/openspec/changes/<change>/proposal.md`.
/// When the active-path fallback yields a parseable `## Why`, emit a
/// per-change WARN so operators can correlate the PR with the likely
/// upstream archive failure. Returns `None` if both paths miss or
/// neither yields a `## Why` heading; no WARN fires in those cases.
pub(crate) fn read_change_why(workspace: &Path, change: &str) -> Option<String> {
    if let Some(why) = read_proposal_why_from_archive(workspace, change) {
        return Some(why);
    }
    let active = workspace
        .join("openspec/changes")
        .join(change)
        .join("proposal.md");
    if active.is_file() {
        let raw = std::fs::read_to_string(&active).ok()?;
        if let Some(why) = extract_why_section(&raw) {
            tracing::warn!(
                change = %change,
                "proposal read from active path, not archive — likely indicates an upstream archive failure for this iteration"
            );
            return Some(why);
        }
    }
    None
}

/// Step 1 of [`read_change_why`]: locate
/// `<workspace>/openspec/changes/archive/*-<change>/proposal.md` (picking
/// the lexicographically last match if multiple exist), read the file,
/// and return its `## Why` section. Returns `None` if the directory or
/// file is missing, the read fails, or no `## Why` heading is present.
fn read_proposal_why_from_archive(workspace: &Path, change: &str) -> Option<String> {
    let archive_root = workspace.join("openspec/changes/archive");
    let entries = std::fs::read_dir(&archive_root).ok()?;
    let suffix = format!("-{change}");
    let mut matches: Vec<std::path::PathBuf> = entries
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name().to_string_lossy().ends_with(&suffix))
        .map(|e| e.path())
        .collect();
    matches.sort();
    let dir = matches.last()?;
    let proposal = dir.join("proposal.md");
    let raw = std::fs::read_to_string(&proposal).ok()?;
    extract_why_section(&raw)
}

/// Pull the `## Why` section out of a proposal.md body: everything from
/// the line after `## Why` up to (but not including) the next `## `
/// heading or EOF. Returns `None` if no `## Why` heading exists.
pub(crate) fn extract_why_section(raw: &str) -> Option<String> {
    let mut lines = raw.lines();
    while let Some(line) = lines.next() {
        if line.trim() == "## Why" {
            let mut out = String::new();
            for next in lines.by_ref() {
                if next.trim_start().starts_with("## ") {
                    break;
                }
                out.push_str(next);
                out.push('\n');
            }
            return Some(out);
        }
    }
    None
}
